require("dotenv").config();
const { Telegraf } = require("telegraf");
const sendRequestToOpenAI = require("./sendRequestToOpenAi");

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);

bot.start((ctx) => {
  ctx.reply(
    "Welcome to the OpenAI Telegram Bot\n\nSend me a message and I will reply to you with a text generated by OpenAI's Davinci model\n\nmade with ❤️ by @agildw"
  );
});

bot.on("text", async (ctx) => {
  const message = ctx.message.text;
  try {
    const response = await sendRequestToOpenAI(message);
    const data = response.data;
    const text = data.choices[0].text.trim();
    ctx.reply(text);
  } catch (err) {
    console.log(err.message);
    ctx.reply("Something went wrong");
  }
});

bot.launch();
console.log("Bot started");
